import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  const newdata = api.posts.getAll.useQuery();
  console.log(newdata.data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col items-center justify-center">
        {user.isSignedIn ? (
          <>body for signed in user</>
        ) : (
          <>body for not signed in user</>
        )}
      </div>
    </>
  );
}
